import { describe, it, expect } from "vitest";
import {
  injectHeader,
  stripHeader,
  detectHeader,
} from "../../src/core/header.js";

describe("injectHeader", () => {
  it("injects HTML comment for markdown", () => {
    const result = injectHeader("# Title\nBody", "commands/commit.md", ".md");
    expect(result).toMatch(/^<!-- AUTO-GENERATED by .+ -->\n# Title\nBody$/);
  });

  it("injects hash comment for YAML", () => {
    const result = injectHeader("key: value", "config.yaml", ".yaml");
    expect(result).toMatch(/^# AUTO-GENERATED by .+\nkey: value$/);
  });

  it("injects // comment for TypeScript", () => {
    const result = injectHeader("const x = 1;", "util.ts", ".ts");
    expect(result).toMatch(/^\/\/ AUTO-GENERATED by .+\nconst x = 1;$/);
  });

  it("injects TOML comment for .toml files", () => {
    const result = injectHeader('key = "value"', "command.toml", ".toml");
    expect(result).toMatch(/^# AUTO-GENERATED by .+\nkey = "value"$/);
  });

  it("returns content unchanged for JSON", () => {
    const content = '{"key": "value"}';
    expect(injectHeader(content, "settings.json", ".json")).toBe(content);
  });

  it("includes source path in header", () => {
    const result = injectHeader("body", "agents/debugger.md", ".md");
    expect(result).toContain("Source: agents/debugger.md");
  });
});

describe("stripHeader", () => {
  it("strips HTML header from markdown", () => {
    const input =
      "<!-- AUTO-GENERATED by clai-helpers — DO NOT EDIT. Source: test.md -->\n# Title";
    const result = stripHeader(input, ".md");
    expect(result).toBe("# Title");
  });

  it("returns content unchanged without header", () => {
    const input = "# Title\nBody";
    expect(stripHeader(input, ".md")).toBe(input);
  });

  it("returns JSON content unchanged", () => {
    const input = '{"key": "value"}';
    expect(stripHeader(input, ".json")).toBe(input);
  });

  it("round-trips: inject then strip", () => {
    const original = "# Title\nBody content here";
    const injected = injectHeader(original, "test.md", ".md");
    const stripped = stripHeader(injected, ".md");
    expect(stripped).toBe(original);
  });
});

describe("detectHeader", () => {
  it("detects valid markdown header", () => {
    const content =
      "<!-- AUTO-GENERATED by clai-helpers — DO NOT EDIT. Source: commands/commit.md -->\n# Title";
    const result = detectHeader(content, ".md");
    expect(result).toEqual({ valid: true, sourcePath: "commands/commit.md" });
  });

  it("returns valid:false for content without header", () => {
    const result = detectHeader("# Just a title", ".md");
    expect(result).toEqual({ valid: false });
  });

  it("returns null for JSON (headerless format)", () => {
    expect(detectHeader('{"key": "value"}', ".json")).toBeNull();
  });

  it("detects hash-style header", () => {
    const content =
      "# AUTO-GENERATED by clai-helpers — DO NOT EDIT. Source: config.yaml";
    const result = detectHeader(content, ".yaml");
    expect(result).toEqual({ valid: true, sourcePath: "config.yaml" });
  });
});
